

# COLUMN에 데이터가 있을때 COLUMN DATA TYPE 변경
> 
1. CREATE temp column
2. UPDATE TO temp column FROM origin column
3. DELETE origin column
4. COMMENT origin column coment

```
ALTER TABLE ESPMDPD ADD TEMP_COLUMN NUMBER(20);
UPDATE ESPMDPD SET TEMP_COLUMN = ORIGIN_COLUMN;
ALTER TABLE ESPMDPD DROP COLUMN ORIGIN_COLUMN;
ALTER TABLE ESPMDPD RENAME COLUMN TEMP_COLUMN TO ORIGIN_COLUMN;
COMMENT ON COLUMN ESPMDPD.ORIGIN_COLUMN IS '커럼명';
```
